services:
  arhitodo:
    image: arhitodo
    build:
      context: .
      dockerfile: Dockerfile

  arhitodo.api:
    image: arhitodo.api
    build:
      context: .
      dockerfile: ArhiTodo.Api/Dockerfile

