services:
  arhitodo.frontend:
    image: ghcr.io/arhigames/arhitodo.frontend:closedalpha
    container_name: arhitodo.frontend
    ports:
      - "5123:5123"
    depends_on:
      - arhitodo.api

  arhitodo.api:
    image: ghcr.io/arhigames/arhitodo.backend:closedalpha
    container_name: arhitodo.api
    environment:
      - ASPNETCORE_HTTP_PORTS=5000;5001
      - ConnectionStrings__DefaultConnection=Host=arhitodo.database;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      - FrontendSettings__BaseUrl=${BASE_URL}
      - JWT__Issuer=${BASE_URL}
      - JWT__Audience=${BASE_URL}
      - JWT__SigningKey=${JWT_KEY}
    ports:
      - "8080:5000"
      - "8081:5001"
    depends_on:
      arhitodo.database:
        condition: service_healthy

  arhitodo.database:
    image: postgres:18
    container_name: arhitodo.database
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./db:/var/lib/postgresql
