services:
  arhitodo.frontend:
    image: ghcr.io/arhigames/arhitodo.frontend:closedalpha
    container_name: arhitodo.frontend
    ports:
      - "5123:5123"
    depends_on:
      - arhitodo.api
  
  arhitodo.api:
    image: ghcr.io/arhigames/arhitodo.backend:closedalpha
    container_name: arhitodo.api
    environment:
      - ASPNETCORE_HTTP_PORTS=5000;5001
      - ConnectionStrings__DefaultConnection=Host=arhitodo.database;Database=boarddb;Username=username;Password=password
      - FrontendSettings__BaseUrl=
      - JWT__Issuer=
      - JWT__Audience=
      - JWT__SigningKey=344faccb39583f6bfb9c22ac46167f828262165f18ef9cdfb96d34d3fc6e72ef0f32bc46a240a2fc99c496fa1f99e9d4f3195831e78a84e9092cb4e7249d797c
    ports:
      - "8080:5000"
      - "8081:5001"
    depends_on:
      arhitodo.database:
        condition: service_healthy

  arhitodo.database:
    image: postgres:18-alpine
    container_name: arhitodo.database
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=boarddb
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d boarddb"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: